language: python
cache: pip
python:
- '3.5'
script: true
notifications:
  email: false
deploy:
  provider: heroku
  app: dank-bot-420
  on:
    repo: Cretezy/DankBot
  api_key:
    secure: oVxL8Y3J+z/f3Az7yB/1gn5iKURXxR/2EYz3X9JK1xOtkn6KgRxg02irYSBd3uzw6yXAXdgr+v4tGjlZyJg7DfjrFlRZumr0z6TQ2iHo8O64T+9hBnz8PCAv8DxBIqwURV4rvCdtmg/GsNlar53BFGSi+uogJfGsTqfl9Hxwxo8UPBz1CwmCUkT52yoBr0jBOyAgMPXaXAULVNT9fcZQlnhuFNXnVq+Mhrroeq41uBKS96S2Jb3QKLKS8tr2SuoSZJMV0rNE1BZHKxWxP6y06JchOb33e6ECrnrBv3vcyS8Ipn8Pxfq7cvZlaBN3e0xcnwvMC9XRfN2REaza2R5SwRgELrYtIQz6iU36QXH/7sC1IAAOte9ZmZOEfLeA0QPRP4XfEk+PQXbAV4hLJ9orP5WOduYuJNe0urS2FlXsuWqElx0PdaNkQcix7hMOPwqISxstCvxNehoYqpcZGGdjOZkubSpB/972y74PFBe/1X1nXk6T7v8b4vTyOkThferDKE5bfd7CwmGIqVIXPxvLeDm3Ue9SFbNbTWg/JTrWMoMYpOHh3VAU4mvZRqH9gZEJbUwL76BywehLngaeGFSnP/PDjLWwvEuXhAWzzA74wAlUTnGjSznsBJF1W8Sb1LY1vpOlYQEAKIkcknrGLCyxX3mgOHh2LN4yw2qbUVu310A=